### ISSUE TITLE
Consider standarizing the source code

### ISSUE THREAD

**Issue by NicolasIriarte** [Satomatic/LoonixEditor#3]
I review your source code and I found that you only use "*.cpp" files instead of cpp/hpp files, is a very bad practice make this. Read [this](https://stackoverflow.com/questions/1686204/why-should-i-not-include-cpp-files-and-instead-use-a-header) for more info. Try to fix this before the projects grow.

**Comment by vekett** [comment]
Just so you know you're not being ignored, @Satomatic is looking into this. :)

**Comment by Satomatic** [comment]
Hello,
Thanks for the advice, I've come to realise how important header files are in the C language and have started to fully use them in my more recent projects which I may push to GitHub soon. I currently don't have plans to run through the LoonixEditor source code and create header files.
This was my first real c++ project so most of it does rely on bad practices such as stitching the code together with externs.
I'll try to get it done at some point but its not a huge focus right now.

Thank again,
-Brian
